### ISSUE TITLE
housing for Adapter

### ISSUE THREAD

**Issue by JojoS62** [yingchao-chen/STLinkV3_Adapter#2]
I have created a small box that can be 3D printed:
https://www.thingiverse.com/thing:5101077

Thanks for this nice board design.

**Comment by yingchaotw** [comment]
Thank you for designed the case, it's so cute!

![STLINK-ADAPTER-CASE](https://user-images.githubusercontent.com/25223663/187842153-14b38bb2-a5fd-4489-b958-354e9055b038.jpg)
